package com.theninjadev.taskflowapi.enums;

public enum ActionType {
    TASK_CREATED,
    TASK_MOVED,
    TASK_UPDATED,
    TASK_DELETED,
    LIST_CREATED,
    LIST_RENAMED,
    LIST_DELETED,
    PRIORITY_CHANGED,
    ASSIGNEE_CHANGED,
    MEMBER_INVITED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    COMMENT_ADDED,
    BOARD_CREATED
}
